// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConfigValue(arg1) {
  return window['go']['main']['App']['GetConfigValue'](arg1);
}

export function GetSpeed(arg1) {
  return window['go']['main']['App']['GetSpeed'](arg1);
}

export function GetTotalTraffic() {
  return window['go']['main']['App']['GetTotalTraffic']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
