// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfigValue(arg1:string):Promise<string>;

export function GetSpeed(arg1:string):Promise<string>;

export function GetTotalTraffic():Promise<string>;

export function SetConfig(arg1:string):Promise<Error>;
